// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX1p7DAgqXEOICfD8FNOHsD16MwLkSFNI',
    appId: '1:1032206180590:android:0f45d6deb28d364008d3ff',
    messagingSenderId: '1032206180590',
    projectId: 'zoope-fe18c',
    storageBucket: 'zoope-fe18c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrTNHN_waqxVN3Tu5wTMGiDEeMsi3_FMI',
    appId: '1:1032206180590:ios:5fb16db83b88ce6508d3ff',
    messagingSenderId: '1032206180590',
    projectId: 'zoope-fe18c',
    storageBucket: 'zoope-fe18c.appspot.com',
    androidClientId: '1032206180590-3p5ubdjqr7tertd1mopli3109fihe4hs.apps.googleusercontent.com',
    iosClientId: '1032206180590-33bi8uldnn8bj5lbabp4q0pp93kmp46h.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
